
// IMPORT SERVICE
// SHOW CONTRACT SSTATE (LOCKED, CONFIRMED, FRIGJORT)
// BUTTON: "LOCK IN" - lock()
// BUTTON: "CONFIRM" - confirm()

// VIEW:
// SHOW ESSCROW-CONTRACTS BETWEEN 2 PARTS
// 3 VIZ OF STATES
// LCOK IN COIN TO SEAL AMOUNT IN CONTRACT
// CONFIRM BTN TO TRIGGER PAYMENT 
// SHOW CURRENT STATE AND BY WHOM